{text: 'Java', value: 'java'},
{text: 'Swift', value: 'swift'},
{text: 'Python', value: 'python'},
{text: 'HTML/XML', value: 'markup'},
{text: 'CSS', value: 'css'},
{text: 'JavaScript', value: 'javascript'},
{text: 'JSON', value: 'json'},
{text: 'PHP', value: 'php'},
{text: 'SQL', value: 'sql'},
{text: 'YAML', value: 'yaml'},
{text: '{{ __('Plaintext') }}', value: 'text'},
